services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: img-placeholder
    ports:
      - "4000:4000"
    volumes:
      - ./public:/app/public
      - ./views:/app/views
    environment:
      - ENV_VAR=value
    restart: unless-stopped